PROJECT_NAME= Sortingalgo
TEST_PROJECT_NAME= Test_$(PROJECT_NAME)

BUILD= build 

SRC = Main.c\

INC= -Include\
	-Iunity\



INCLUDE_LIBS = -Icunit

PROJECT_OUTPUT=$(BUILD)/$(PROJECT_NAME).out 

$(PROJECT_NAME):all

all: $(SRC) $(BUILD)
		gcc $(SRC) $(INC) -o $(PROJECT_OUTPUT).out



$(BUILD):
			mkdir build